version: 0.2

env:
  variables:
    AWS_REGION_2: "us-east-2"
    REACT_APP_API_SERVICE_URL: "http://flask-react-alb2-146681863.us-east-1.elb.amazonaws.com"
    WEBAPP_API_SERVICE_URL: "http://rockstar-alb-1903077144.us-east-1.elb.amazonaws.com"

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub to avoid rate limits...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo logging in to ecr...
      - aws sts get-caller-identity
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo building all images using docker-compose...
      - docker-compose build

  post_build:
    commands:
      - echo pushing images to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/depthanythingflask/api:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yoloflask/api:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/objectdetectionreact/webapp:prod
      - echo "Build completed on `date`"
