version: 0.2

env:
  variables:
    AWS_REGION_2: "us-east-2"
    REACT_APP_API_SERVICE_URL: "http://http://flask-react-alb2-146681863.us-east-1.elb.amazonaws.com"
    WEBAPP_API_SERVICE_URL: "http://rockstar-alb-1903077144.us-east-1.elb.amazonaws.com"

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub to avoid rate limits...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo building dev images...
      - docker-compose up -d --build
      - echo building prod images...
      - >
        docker build \
          -f depth-anything-flask-app/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/depthanythingflask/api:prod \
          --build-arg FLASK_ENV=production \
          ./depth-anything-flask-app
      - >
        docker build \
          -f yolo-v5-flask-app/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yoloflask/api:prod \
          --build-arg FLASK_ENV=production \
          ./yolo-v5-flask-app
      - >
        docker build \
          -f object-detection-react-app/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/objectdetectionreact/webapp:prod \
          --build-arg FLASK_ENV=production \
          ./object-detection-react-app
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/depthanythingflask/api:prod
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yoloflask/api:prod
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/objectdetectionreact/webapp:prod
