version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"  # Corrected from AWS_REGION_2
    REACT_APP_API_SERVICE_URL: "http://flask-react-alb2-146681863.us-east-1.elb.amazonaws.com"
    WEBAPP_API_SERVICE_URL: "http://rockstar-alb-1903077144.us-east-1.elb.amazonaws.com"

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo Logging into Amazon ECR...
      - aws sts get-caller-identity
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building all images with docker-compose...
      - docker-compose build
      - echo Tagging images...
      - docker tag object-detection-react-app_frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/objectdetectionreact/webapp:prod
      - docker tag yolo-v5-flask-app_yoloapi:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yoloflask/api:prod
      - docker tag depth-anything-flask-app_depthapi:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/depthanythingflask/api:prod

  post_build:
    commands:
      - echo Pushing tagged images to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/depthanythingflask/api:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/yoloflask/api:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/objectdetectionreact/webapp:prod
      - echo Build completed on `date`
