version: '3.8'

services:
  frontend:
    build:
      context: ./object-detection-react-app
      dockerfile: Dockerfile
    image: object-detection-react-app_frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - yoloapi
      - depthapi
    networks:
      - app-network

  yoloapi:
    build:
      context: ./yolo-v5-flask-app
      dockerfile: Dockerfile
    image: yolo-v5-flask-app_yoloapi:latest
    ports:
      - "5000:5000"
    networks:
      - app-network

  depthapi:
    build:
      context: ./depth-anything-flask-app
      dockerfile: Dockerfile
    image: depth-anything-flask-app_depthapi:latest
    ports:
      - "5050:5050"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
